# Generated by Django 6.0 on 2025-12-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='context',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='context',
            new_name='content',
        ),
    ]
