# Generated by Django 6.0 on 2025-12-30 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_rename_context_review_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryReaction',
            new_name='Reaction',
        ),
        migrations.AlterField(
            model_name='review',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
