# Generated by Django 6.0 on 2025-12-31 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_rename_storyreaction_reaction_alter_review_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(max_length=3000),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('story', 'alias'), name='unique_alias_per_story'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'story'), name='unique_review_per_user_per_story'),
        ),
    ]
