# Generated by Django 6.0 on 2026-01-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_review_options_alter_story_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='no_of_ratings',
            new_name='total_ratings',
        ),
    ]
