# Generated by Django 6.0 on 2026-02-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_rename_no_of_ratings_story_total_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('mystery', 'Mystery'), ('fiction', 'Fiction'), ('comedy', 'Comedy'), ('others', 'Others')], default='others', max_length=7),
        ),
    ]
