# Generated by Django 6.0 on 2026-02-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_alter_story_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
