# Generated by Django 6.0 on 2025-12-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_authors_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pen_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
