# Generated by Django 6.0 on 2025-12-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
